"""fix: update saleModel date default to dateTime now and ProductModel  stablieshment collumn for stablishment

Revision ID: 2e136d7fb5c1
Revises: d25a7edd3aea
Create Date: 2022-05-05 12:44:28.391651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e136d7fb5c1'
down_revision = 'd25a7edd3aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('establishment_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_establieshment_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'establishments', ['establishment_id'], ['id'])
    op.drop_column('products', 'establieshment_id')
    op.alter_column('sales', 'paid_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sales', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'sale_total',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('sales', 'remain_to_pay',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('sales_products', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_products', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'remain_to_pay',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales', 'sale_total',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'paid_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('products', sa.Column('establieshment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_establieshment_id_fkey', 'products', 'establishments', ['establieshment_id'], ['id'])
    op.drop_column('products', 'establishment_id')
    # ### end Alembic commands ###
