"""update password to password_hash

Revision ID: 589240cc669f
Revises: ab23e79319e2
Create Date: 2022-04-28 11:47:04.189344

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "589240cc669f"
down_revision = "ab23e79319e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "establishments", ["user_id"])
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "contact", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "users", "contact", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_column("users", "password_hash")
    op.drop_constraint(None, "establishments", type_="unique")
    # ### end Alembic commands ###
