"""establishment_id unique set to False on clients table

Revision ID: 7873949ecbc6
Revises: 659011afb05d
Create Date: 2022-05-02 17:53:18.967429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7873949ecbc6'
down_revision = '659011afb05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_establishment_id_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_establishment_id_key', 'clients', ['establishment_id'])
    # ### end Alembic commands ###
