"""fix: sale date default

Revision ID: 856d7ffd0902
Revises: d25a7edd3aea
Create Date: 2022-05-05 17:25:58.482762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '856d7ffd0902'
down_revision = 'd25a7edd3aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'paid_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sales', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'sale_total',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('sales', 'remain_to_pay',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('sales_products', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_products', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'remain_to_pay',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales', 'sale_total',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('sales', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'paid_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
