"""update 3

Revision ID: 91d6b700eb0c
Revises: ba793a2a2d91
Create Date: 2022-04-21 18:45:40.605988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d6b700eb0c'
down_revision = 'ba793a2a2d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'establishments', 'users', ['user_id'], ['id'])
    op.add_column('product_categories', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('product_categories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_categories', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_categories', 'categories', ['category_id'], ['id'])
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('establieshment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'establishments', ['establieshment_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.add_column('sales', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'sales', ['payment_id'])
    op.create_foreign_key(None, 'sales', 'payments', ['payment_id'], ['id'])
    op.add_column('sales_products', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.add_column('sales_products', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'sales_products', 'sales', ['sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_products', type_='foreignkey')
    op.drop_constraint(None, 'sales_products', type_='foreignkey')
    op.drop_column('sales_products', 'product_id')
    op.drop_column('sales_products', 'sale_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='unique')
    op.drop_column('sales', 'payment_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'establieshment_id')
    op.drop_column('products', 'category_id')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_column('product_categories', 'category_id')
    op.drop_column('product_categories', 'product_id')
    op.drop_constraint(None, 'establishments', type_='foreignkey')
    op.drop_column('establishments', 'user_id')
    # ### end Alembic commands ###
