"""fix: modification tables

Revision ID: ab23e79319e2
Revises: aada81c7c532
Create Date: 2022-04-25 14:56:58.493776

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab23e79319e2"
down_revision = "aada81c7c532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("url_img", sa.String(), nullable=True))
    op.drop_column("categories", "Image")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("Image", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("categories", "url_img")
    # ### end Alembic commands ###
