"""fix: changed unique user_id from True to False

Revision ID: d7fe98c16d22
Revises: 589240cc669f
Create Date: 2022-04-28 15:34:07.474979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7fe98c16d22"
down_revision = "589240cc669f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("establishments_user_id_key", "establishments", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "establishments_user_id_key", "establishments", ["user_id"]
    )
    # ### end Alembic commands ###
