"""fix: some columns from addresses and establishments tables changed to nullable=False

Revision ID: ecbfbae4e149
Revises: 0396f1f973a9
Create Date: 2022-04-29 18:29:00.063860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbfbae4e149'
down_revision = '0396f1f973a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('adresses', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('adresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('adresses', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('establishments', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('establishments', 'cnpj',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('establishments', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishments', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('establishments', 'cnpj',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('establishments', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('adresses', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('adresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('adresses', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('adresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
